### ISSUE TITLE
翻訳が不足している箇所がすぐわかるようにする

### ISSUE THREAD

**Issue by kfly8** [perldoc-jp/translation#38]
# 概要

翻訳をしたいと思ってもどこから取り組んでよいかわからないかもしれない。
そこで、Good first issueといった初めての人でも最初に取り組んだら良さそうな翻訳箇所がわかるようにする。
具体的な方法は、以下のような案から選択する
- perldocと翻訳データの差分を取って issueなどに登録？
- 翻訳データがない場合は、最新の英文を表示する？

# 目的

- 翻訳が初めての人でも最初に取り組んだら良さそうな翻訳箇所がわかりやすくなること、案内しやすくなること

# タスク

WIP: 具体的な方法次第

**Comment by kfly8** [comment]
次の一覧ページでリンク先切れになっているページが、翻訳していないページを洗い出すのに良いということがわかりました。
perldoc.jp の t/endpoints.t で、$mech->page_links_ok を使えば、すぐ洗い出せます。

- https://perldoc.jp/index/core
- https://perldoc.jp/index/function
- https://perldoc.jp/index/variable

これによって、次のページで翻訳ができてないことがわかりました！
- https://github.com/perldoc-jp/translation/issues/116
- https://github.com/perldoc-jp/translation/issues/117
- https://github.com/perldoc-jp/translation/issues/118

こういった簡易的な方法でも今は十分だと思ったのですがいかがでしょう？
良さそうであれば、ちょっとドキュメンテーションはしつつ、このチケット閉じて良いかなーと。
@AnaTofuZ @melonsode

**Comment by argrath** [comment]
(このissue気づいてませんでした)

> また、本家はバージョンごとにページが生成される。バージョン間での差異がどの程度あるのかわからないが、いま見ている文章が最新のものかどうか不安にならずに済む方法はないか？

ページ右上にバージョンが出ていて、他バージョンへのリンクもあります。

> Perlのバージョン変更情報がperldoc.jpにはないようにように思われる。ここを重点的に翻訳することで、perlのバージョンごとの差異の情報を見つけやすくなるのではななかろうか。 https://perldoc.perl.org/5.34.1/perl#History

あります。
https://perldoc.jp/docs/perl/5.38.0/perl5380delta.pod

**Comment by argrath** [comment]
> これによって、次のページで翻訳ができてないことがわかりました！

atan2, qw/STRING/, qx/STRING/ とも https://perldoc.jp/docs/perl/5.38.0/perlfunc.pod にはあるので、
切り出し処理の問題のように見えます。

**Comment by kfly8** [comment]
組み込み関数の翻訳は、https://perldoc.jp/docs/perl/XXX/perlfunc.pod から切り取られるような仕組みになってるですねー。
perldoc.jp の切り出し処理追ってみます。

**Comment by kfly8** [comment]
コアドキュメント、組み込みの関数、変数に関しては、翻訳が不足しているケースをテストで認知できるようになった。

**Comment by kfly8** [comment]
テストで翻訳の不足を認知できるようになったので、
このissueのタイトルの通り「翻訳が不足している箇所がすぐわかるようにする」は、一旦の解決としたいと思います。

その他にもissue内に問題と感じているケースがありそうですが、
進行が滞っている状況も踏まえ、改めて起案いただいて対応するのが良さそうだと思いました！
